#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse, os, textwrap

def to_c_identifier(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == '_':
            out.append(ch)
        else:
            out.append('_')
    ident = ''.join(out)
    if ident and ident[0].isdigit():
        ident = '_' + ident
    return ident

def emit_c_array(bin_data: bytes, array_name: str, bytes_per_line: int = 16) -> str:
    lines = []
    lines.append(f"const uint8_t {array_name}[] = {{")
    for i in range(0, len(bin_data), bytes_per_line):
        chunk = bin_data[i:i+bytes_per_line]
        hexes = ', '.join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hexes},")
    lines.append("};")
    return '\n'.join(lines)

TEMPLATE_V9 = """\
/* Auto-generated by vpg2lvimg.py — LVGL v9 image descriptor wrapping a .vpg blob */
#include "{inc}"

#if !defined(LVGL_VERSION_MAJOR) || (LVGL_VERSION_MAJOR < 9)
#error "This file was generated for LVGL v9. Use --lv 8 for LVGL v8."
#endif

{storage} {array}

{storage} lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf    = LV_COLOR_FORMAT_RAW,
        .flags = 0,
        .w     = {w},
        .h     = {h},
    }},
    .data_size = sizeof({name}_data),
    .data      = {name}_data,
}};
"""

TEMPLATE_V8 = """\
/* Auto-generated by vpg2lvimg.py — LVGL v8 image descriptor wrapping a .vpg blob */
#include "{inc}"

#if !defined(LVGL_VERSION_MAJOR) || (LVGL_VERSION_MAJOR != 8)
#warning "This file targets LVGL v8 (lv_img_dsc_t)."
#endif

{storage} {array}

{storage} lv_img_dsc_t {name} = {{
    .header.always_zero = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = sizeof({name}_data),
    .header.cf = LV_IMG_CF_RAW,   /* RAW for v8 */
    .data = {name}_data,
}};
"""

HEADER_TEMPLATE = """\
/* Auto-generated by vpg2lvimg.py */
#pragma once
#include "{inc}"
#ifdef __cplusplus
extern "C" {{
#endif
extern const {ty} {name};
#ifdef __cplusplus
}}
#endif
"""

def main():
    ap = argparse.ArgumentParser(
        description="Wrap a .vpg file into an LVGL image descriptor (no decoding).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
        Examples:
          python vpg2lvimg.py input.vpg -o vpg_blob.c -n my_vpg_blob --lv 9
          python vpg2lvimg.py input.vpg -o vpg_blob.c -n my_vpg_blob --lv 8 --width 360 --height 360
        """)
    )
    ap.add_argument("input", help=".vpg file path")
    ap.add_argument("-o", "--out", required=True, help="output .c file path")
    ap.add_argument("-n", "--name", required=True, help="C symbol base name")
    ap.add_argument("--lv", choices=["8","9"], default="9", help="LVGL major version to target")
    ap.add_argument("--width", type=int, default=1, help="descriptor width (default 1)")
    ap.add_argument("--height", type=int, default=1, help="descriptor height (default 1)")
    ap.add_argument("--inc", default="lvgl.h", help="header to include (default: lvgl.h)")
    ap.add_argument("--static", action="store_true", help="make symbols static")
    ap.add_argument("--header", default=None, help="optional .h path to emit extern")
    args = ap.parse_args()

    sym = to_c_identifier(args.name)
    array_name = f"{sym}_data"
    storage = "static" if args.static else "/* not static */"

    with open(args.input, "rb") as f:
        data = f.read()

    array_code = emit_c_array(data, array_name)

    if args.lv == "9":
        body = TEMPLATE_V9.format(
            inc=args.inc, storage=storage, array=array_code,
            name=sym, w=args.width, h=args.height
        )
        header_body = HEADER_TEMPLATE.format(
            inc=args.inc, ty="lv_image_dsc_t", name=sym
        )
    else:
        body = TEMPLATE_V8.format(
            inc=args.inc, storage=storage, array=array_code,
            name=sym, w=args.width, h=args.height
        )
        header_body = HEADER_TEMPLATE.format(
            inc=args.inc, ty="lv_img_dsc_t", name=sym
        )

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fo:
        fo.write(body)

    if args.header:
        with open(args.header, "w", encoding="utf-8") as fh:
            fh.write(header_body)

    print(f"Generated: {args.out}")
    if args.header:
        print(f"Generated: {args.header}")

if __name__ == "__main__":
    main()
