#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_

#if 0
#define LT_DEV_NAME      "设备名称"
#define LT_SOFT_VER      "软件版本"
#define LT_BUILD_DAY     "构建日期"
#define LT_DEVICE_ID     "设备ID"
#define LT_INFO          "信息"

#define LT_XIAOLE        "小乐"
#define LT_MUSIC         "音乐"
#define LT_ALARM         "闹钟"
#define LT_SETTING       "设置"
#define LT_GENERA       "通用"
#define LT_LIGHT         "应援灯"
#define LT_ANIM          "动画"
#define LT_TIMBRE        "角色"
#define LT_HELP          "帮助"
#define LT_SYS_INFO      "系统信息"
#define LT_PC_MODE       "PC模式"
#define LT_ADD_ALARMS   "添加闹钟"
#define LT_EDIT_ALARMS   "闹钟编辑"
#define LT_TIME          "时间"
#define LT_CYCLE         "重复"


#define LT_BACK           "返回"
#define LT_ACCEPT         "确定"
#define LT_CANCEL         "取消"
#define LT_SYSTEM         "系统"
#define LT_LAB            "实验室"
#define LT_ROLE_SETTING   "角色设置"
#define LT_MUSIC_LIST     "音乐列表"
#define LT_LIST_EMPTY     "音乐列表为空"
#define LT_APPLY_SETTING  "应用中..."
#define LT_APPLY_FAIL     "设置失败,请重试"
#define LT_LOADING        "加载中..."
#define LT_LOADING_FAIL   "加载失败，请重试"
#define LT_CONNECT_PHONE_FIRST  "请先连接手机"
#define LT_NET_ERR          "网络异常"
#define LT_RECOVER        "恢复出厂设置"
#define LT_CONN_PHONE     "连接手机"
#define LT_AI_THEME       "助手主题"
#define LT_AUTO_SHUTDOWN  "自动关机"
#define LT_MUSIC_TITLE    "暂无歌曲"

#define LT_LAB_FUNC         "实验功能"
#define LT_GLOBAL_WAKE      "全局语音唤醒"
#define LT_GLOBAL_WAKE_MSG  "可能导致播放音乐时误唤醒"

#define LT_CONNECT          "配对模式"
#define LT_CONNECTED          "已连接"
#define LT_SEARCH_AND_CONNECT   "请在手机上搜索并连接设备"
#define LT_USE_HELP             "使用说明"
#define LT_SCAN_GET_HELP        "扫描二维码获取更多帮助"
#define LT_ACT_DEV_CODE         "请登录到后台\r\n输入设备码:%s"

#define LT_THEME_SET  "主题设置"
#define LT_THEME_2  "Robot"
#define LT_THEME_1  "Gundam"

#define LT_WEEK_1   "一"
#define LT_WEEK_2   "二"
#define LT_WEEK_3   "三"
#define LT_WEEK_4   "四"
#define LT_WEEK_5   "五"
#define LT_WEEK_6   "六"
#define LT_WEEK_7   "日"

#define LT_NERVER   "从不"
#define LT_5_MIN    "5分钟"
#define LT_10_MIN   "10分钟"
#define LT_30_MIN   "30分钟"
#define LT_1_HOUR   "1小时"
#define LT_2_HOUR   "2小时"
#define LT_3_HOUR   "3小时"
#define LT_4_HOUR   "4小时"
#define LT_5_HOUR   "5小时"
#define LT_6_HOUR   "6小时"

#define LT_ALARM_WEEK_1   "一"
#define LT_ALARM_WEEK_2   "二"
#define LT_ALARM_WEEK_3   "三"
#define LT_ALARM_WEEK_4   "四"
#define LT_ALARM_WEEK_5   "五"
#define LT_ALARM_WEEK_6   "六"
#define LT_ALARM_WEEK_7   "日"
#define LT_EVERY_DAY   "每天"
#define LT_ONLY_ONCE   "单次"

#define LT_ACTIVATE         "欢迎使用"
#define LT_SWIP_TO_START    "向左轻扫以开始"
#define LT_SCAN_QR_FOR_HELP    "扫码查看连接步骤"
#define LT_WAIT_BT_CONNECT    "等待连接..."
#define LT_WAIT_NET_CONNECT    "联网中..."
#else
#define LT_DEV_NAME      "Device Name"
#define LT_SOFT_VER      "Software Version"
#define LT_BUILD_DAY     "Build Date"
#define LT_DEVICE_ID     "Device ID"
#define LT_INFO          "Information"

// #define LT_REPEAT       ""

#define LT_XIAOLE        "Xiaole"
#define LT_MUSIC         "Music"
#define LT_ALARM         "Alarm"
#define LT_SETTING       "Settings"
#define LT_GENERA       "Genera"
#define LT_LIGHT         "Cheering Light"
#define LT_ANIM          "Animation"
#define LT_TIMBRE        "Character"
#define LT_HELP          "Help"
#define LT_SYS_INFO      "System Info"
#define LT_PC_MODE       "PC Mode"
#define LT_ADD_ALARMS   "Add Alarms"
#define LT_EDIT_ALARMS   "Edit Alarms"
#define LT_TIME         "Time"
#define LT_CYCLE         "Cycle"


#define LT_BACK           "Back"
#define LT_ACCEPT         "OK"
#define LT_CANCEL         "Cancel"
#define LT_SYSTEM         "System"
#define LT_LAB            "Lab"
#define LT_ROLE_SETTING   "Character Settings"
#define LT_LIST_EMPTY     "List is empty"
#define LT_MUSIC_LIST     "List"
#define LT_APPLY_SETTING  "Applying settings..."
#define LT_APPLY_FAIL     "Failed to apply settings. Please try again."
#define LT_CONNECT_PHONE_FIRST  "Please connect your phone first."
#define LT_NET_ERR          "Network Error."
#define LT_LOADING        "Loading..."
#define LT_LOADING_FAIL   "Failed to load. Please try again later."
#define LT_RECOVER        "Factory Reset"
#define LT_CONN_PHONE     "Connect Phone"
#define LT_AI_THEME       "Assistant Theme"
#define LT_AUTO_SHUTDOWN  "Auto Shutdown"
#define LT_MUSIC_TITLE    "Music"

#define LT_LAB_FUNC         "Lab Features"
#define LT_GLOBAL_WAKE      "Global Voice Wake"
#define LT_GLOBAL_WAKE_MSG  "May cause false wake-up"

#define LT_USE_HELP         "User Guide"
#define LT_CONNECT          "Connect Phone"
#define LT_CONNECTED          "Connected"
#define LT_SEARCH_AND_CONNECT   "Search for and connect to the device on your phone."
#define LT_SCAN_GET_HELP    "Scan the QR code for more help"

#define LT_THEME_SET  "Theme Settings"
#define LT_THEME_1    "Robot"
#define LT_THEME_2    "Gundam"

#define LT_WEEK_1   "Mon"
#define LT_WEEK_2   "Tue"
#define LT_WEEK_3   "Wed"
#define LT_WEEK_4   "Thu"
#define LT_WEEK_5   "Fri"
#define LT_WEEK_6   "Sat"
#define LT_WEEK_7   "Sun"

#define LT_NERVER   "Nerver"
#define LT_5_MIN    "5 Minutes"
#define LT_10_MIN   "10 Minutes"
#define LT_30_MIN   "30 Minutes"
#define LT_1_HOUR   "1 Hour"
#define LT_2_HOUR   "2 Hours"
#define LT_3_HOUR   "3 Hours"
#define LT_4_HOUR   "4 Hours"
#define LT_5_HOUR   "5 Hours"
#define LT_6_HOUR   "6 Hours"

#define LT_ALARM_WEEK_1   "Mon "
#define LT_ALARM_WEEK_2   "Tue "
#define LT_ALARM_WEEK_3   "Wed "
#define LT_ALARM_WEEK_4   "Thu "
#define LT_ALARM_WEEK_5   "Fri "
#define LT_ALARM_WEEK_6   "Sat "
#define LT_ALARM_WEEK_7   "Sun "
#define LT_EVERY_DAY   "Every Day"
#define LT_ONLY_ONCE   "Only Once"


#define LT_ACTIVATE     "Hello"
#define LT_SWIP_TO_START    "Swipe left to start."
#define LT_SCAN_QR_FOR_HELP    "Scan the QR code for instructions."
#define LT_WAIT_BT_CONNECT    "Waiting for connection...."
#define LT_WAIT_NET_CONNECT    "Connecting..."
#endif
#endif